---
title: "Mauna Loa Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_mauna_loa}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(zoomerGP)
library(ggplot2)
library(tibble)
library(dplyr)
```

This vignette shows users how to reproduce the Mauna Loa Atmospheric Carbon Dioxide data analysis example from Rasmussen and Williams (2006, p 118-120) using `zoomerGP`. 

```{r}
regression_data <- tibble(
  co2 = (c(co2) - mean(co2))/3*sd(co2)
) %>% 
  mutate(t = 1970 + as.numeric(row_number())/12)
head(regression_data)
```

```{r}
regression_data  %>%
  ggplot(aes(x=t, y=co2)) + 
  geom_point() + 
  theme_bw() + 
  ggtitle("Co2 concentration over time") + 
  xlab("Year")
```

```{r}
gpr_model <- gaussian_process(co2 ~ rbf(t)+ spectral1(t), data = regression_data, training_method = "bfgs")
gpr_model$gpr_object$log_like(TRUE)$get_x()
gpr_model
```


```{r}
new_data <- tibble(t = seq(1970,2020,.25))
predictions <- predict(gpr_model, new_data)

new_data$predictions <- predictions[,1]
new_data$ci_upper <- predictions[,1] + 2*sqrt(predictions[,2])
new_data$ci_lower <- predictions[,1] - 2*sqrt(predictions[,2])

ggplot() + 
  geom_point(data = regression_data, aes(x = t, y=co2)) + 
  geom_line(data = new_data, aes(x = t, y = predictions)) + 
  geom_line(data = new_data, aes(x = t, y = ci_upper), linetype = 2) + 
  geom_line(data = new_data, aes(x = t, y = ci_lower), linetype = 2) + 
  theme_bw()

  
```
