# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_zoomerGP_wrappers", use_symbols = TRUE, package_name = "zoomerGP")

#' @usage NULL
#' @useDynLib zoomerGP, .registration = TRUE
NULL

GPRegression <- new.env(parent = emptyenv())

GPRegression$r_new <- function(x, y, kernel_specification) .Call(wrap__GPRegression__r_new, x, y, kernel_specification)

GPRegression$r_update <- function() invisible(.Call(wrap__GPRegression__r_update, self))

GPRegression$r_log_like <- function() .Call(wrap__GPRegression__r_log_like, self)

GPRegression$r_log_like_and_grad <- function() .Call(wrap__GPRegression__r_log_like_and_grad, self)

GPRegression$r_display_kernel <- function() invisible(.Call(wrap__GPRegression__r_display_kernel, self))

GPRegression$r_optimize <- function(max_iter, use_constraints) invisible(.Call(wrap__GPRegression__r_optimize, self, max_iter, use_constraints))

#' @export
`$.GPRegression` <- function (self, name) { func <- GPRegression[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GPRegression` <- `$.GPRegression`


# nolint end
